### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by alecmocatta** [Aaron1011/spawn-pidfd#1]
Hi @Aaron1011 

Cool little library! I just came across it and wondering if you'd consider making it available under an open source license?

p.s. I don't know of a platform which this would affect but I believe https://github.com/Aaron1011/spawn-pidfd/blob/44c40733905b0d793ac8393079ecb393774cedda/src/lib.rs#L61 should have `libc::c_char` changed to `libc::c_int` or `[libc::c_int; 1]`.

**Comment by Aaron1011** [comment]
@alecmocatta: I didn't think that anyone would actually find this useful in its current state :smile: 

I've added an MIT license.
